# Generated by Django 3.1 on 2020-11-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genres',
            field=models.ManyToManyField(related_name='postsgen', to='posts.Genre'),
        ),
    ]
