# Generated by Django 3.1 on 2020-11-14 15:35

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201108_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image_genre',
            field=models.ImageField(default='0', upload_to=posts.models.get_file_path),
            preserve_default=False,
        ),
    ]
