# Generated by Django 3.1 on 2020-11-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_genre_image_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='initial_featured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
