# Generated by Django 3.1 on 2020-12-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_post_content',
            new_name='image_post',
        ),
    ]
