# Generated by Django 3.1 on 2020-12-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201207_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nicknane',
            new_name='nickname',
        ),
    ]
