# Generated by Django 3.1 on 2020-12-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201208_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
