# Generated by Django 3.1 on 2021-01-01 18:39

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201221_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image_genre',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
