# Generated by Django 3.1 on 2021-07-13 22:49

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0015_postrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_image', serialize=False, to='auth.user')),
                ('profile_image', models.ImageField(upload_to=posts.models.get_file_path)),
            ],
        ),
        migrations.AlterField(
            model_name='postrating',
            name='rating',
            field=models.CharField(choices=[('1', 'One star'), ('2', 'Two stars'), ('3', 'Three stars'), ('4', 'Three stars'), ('5', 'Five stars')], max_length=1),
        ),
    ]
