/**
 * Declare action types for reducers
 */
export const GENRES_LOADING = 'GENRES_LOADING';
export const GENRES_FAILED = 'GENRES_FAILED';
export const ADD_GENRES = 'ADD_GENRES';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POSTS = 'POSTS_GENRES';

export const FEATUREDPOSTS_LOADING = 'FEATUREDPOSTS_LOADING';
export const FEATUREDPOSTS_FAILED = 'FEATUREDPOSTS_FAILED';
export const ADD_FEATUREDPOSTS = 'ADD_FEATUREDPOSTS';