/**
 * Declare action types for reducers
 */
export const GENRES_LOADING = 'GENRES_LOADING';
export const GENRES_FAILED = 'GENRES_FAILED';
export const ADD_GENRES = 'ADD_GENRES';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POSTS = 'ADD_POSTS';

export const FEATUREDPOSTS_LOADING = 'FEATUREDPOSTS_LOADING';
export const FEATUREDPOSTS_FAILED = 'FEATUREDPOSTS_FAILED';
export const ADD_FEATUREDPOSTS = 'ADD_FEATUREDPOSTS';

export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';